-- supabase-nudge: per-project keep-alive setup
--
-- Run once per Supabase project in the SQL editor (Dashboard → SQL Editor).
-- Idempotent: safe to re-run on existing projects as a migration.
--
-- Creates a keep_alive table that the scheduled pinger INSERTs into using
-- the project's public anon key. Each ping appends one row; the accumulating
-- rows act as a free audit trail of pings (a few hundred per project per
-- year — no cleanup logic in v1).

CREATE TABLE IF NOT EXISTS public.keep_alive (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note text NOT NULL DEFAULT 'pinged by supabase-nudge',
    pinged_at timestamptz NOT NULL DEFAULT now()
);

-- Migrate pre-existing tables created before pinged_at was added.
ALTER TABLE public.keep_alive
    ADD COLUMN IF NOT EXISTS pinged_at timestamptz NOT NULL DEFAULT now();

-- Migrate pre-existing tables whose id column is the original
-- `integer PRIMARY KEY` (no default). Convert it to GENERATED BY DEFAULT
-- AS IDENTITY so the pinger can POST {} and let the database fill every
-- column. Idempotent: only runs if id isn't already an identity column.
-- Sequence starts above max(id) so it never collides with the original
-- seed row (id=1) on tables that have it.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name   = 'keep_alive'
          AND column_name  = 'id'
          AND is_identity  = 'YES'
    ) THEN
        EXECUTE format(
            'ALTER TABLE public.keep_alive ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
            COALESCE((SELECT max(id) + 1 FROM public.keep_alive), 1)
        );
    END IF;
END
$$;

ALTER TABLE public.keep_alive ENABLE ROW LEVEL SECURITY;

-- anon needs SELECT so PostgREST can return the inserted row when the
-- pinger sends `Prefer: return=representation`. Without this, INSERT
-- returns an empty body and the pinger can't verify the write landed.
DROP POLICY IF EXISTS "anon can select keep_alive" ON public.keep_alive;
CREATE POLICY "anon can select keep_alive"
    ON public.keep_alive
    FOR SELECT
    TO anon
    USING (true);

-- Narrowly-scoped INSERT capability. No UPDATE, no DELETE, no schema
-- modification — anon's blast radius on this project is "append rows
-- to public.keep_alive."
DROP POLICY IF EXISTS "anon can insert keep_alive" ON public.keep_alive;
CREATE POLICY "anon can insert keep_alive"
    ON public.keep_alive
    FOR INSERT
    TO anon
    WITH CHECK (true);
